name: Python Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Ruff
      run: pip install ruff

    - name: Check formatting
      run: ruff check

  build-and-test:
    needs: format-and-check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies using Poetry
      run: poetry install

    - name: Build package using Poetry
      run: poetry build

#    - name: Run tests using Poetry
#      run: poetry run pytest
